apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: volume-from-template
spec:
  params:
    - name: git-url
      type: string
  workspaces:
    - name: codebase
  tasks:
    - name: fetch-from-source         # 内连定义 task 没有引用外部的 task
      params:
        - name: url
          value: $(params.git-url)
      taskSpec:
        workspaces:
          - name: source
        params:
          - name: url
        steps:
          - name: git-clone
            image: alpine/git:v2.32.0
            script: git clone -v $(params.url) $(workspaces.source.path)/source
      workspaces:
        - name: source
          workspace: codebase
    - name: source-lister
      runAfter:
        - fetch-from-source
      taskSpec:
        steps:
          - name: list-files
            image: alpine:3.15
            script: ls $(workspaces.source.path)/source
        workspaces:
          - name: source
      workspaces:
        - name: source
          workspace: codebase
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: volume-from-template-run-xxxxx-001
spec:
  pipelineRef:
    name: volume-from-template
  params:
    - name: git-url
      value: https://gitee.com/mageedu/spring-boot-helloWorld.git
  workspaces:                       # workspace 声明
    - name: codebase                # workspace 名称
      volumeClaimTemplate:          # 动态向 StorageClass:nfs-csi 申请 pvc 持久化存储
        spec:
          accessModes:              # 访问模式
            - ReadWriteOnce         # 以读写方式挂载一次
          resources:
            requests:
              storage: 1Gi          # 申请的存储的大小，只要有大于 1Gi 的PV 存在就可以绑定
          storageClassName: nfs-csi # 使用的存储类是 nfs-csi,是一个 storageClass 对象，它是一个 nfs 驱动会自动帮你创建 pvc 和 pv
