apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: s2i-listener 
spec:
  serviceAccountName: tekton-triggers-gitlab-sa
  triggers:                           # triggers 定义
  - name: gitlab-push-events-trigger
    interceptors:                     # 拦截器定义，关心那类事件
    - ref:
        name: "gitlab"
      params:
      - name: "secretRef"
        value:
          secretName: gitlab-webhook-token 
          secretKey: webhookToken
      - name: "eventTypes"
        value: 
          - "Push Hook"
          - "Tag Push Hook"
          - "Merge Request Hook"
    bindings:                       # 关联 TriggerBinding
    - ref: s2i-binding
    template:                       # 关联 TriggerTemplate
      ref: s2i-tt
