apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: s2i-image-push-run-00001
spec:
  pipelineRef:
    name: source-to-image
  params:
    - name: git-url
      value: https://gitee.com/mageedu/spring-boot-helloWorld.git
    - name: image-url
      value: ikubernetes/spring-boot-helloworld
    - name: image-tag
      value: v0.9.1
  workspaces:
    - name: codebase
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
          storageClassName: nfs-csi
    - name: docker-config
      secret:                           # 引用的是一个 secret 对象，里面有访问我们私有仓库的账号和密码。
        secretName: docker-config
