apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: gitlab-push-binding
spec:
  params:
  - name: git-revision
    value: $(body.checkout_sha)                 # 读取 事件中的字段
  - name: git-repo-url
    value: $(body.repository.git_http_url)      # 读取 事件中的字段
